import * as THREE from 'three';
import {qualityPresets} from './exploration-input.mjs';
import {createTerrainMaterial,createWaterMaterial} from './environment-materials';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {sample as legacySample, terrainColor as legacyColor, riverPaths as legacyRivers, riverLevel as legacyLevel, riverSurface as legacySurface, lakes as legacyLakes, noise} from './terrain.mjs';
import {elaris,extentFor,geographyColor} from './geography.mjs';
import {createGeographicTerrain,createLocalEcology} from './geographic-terrain';
const sample=(id:string,x:number,z:number)=>id==='elaris'?elaris.sample(x,z):legacySample(id,x,z);
const terrainColor=(id:string,p:ReturnType<typeof sample>)=>id==='elaris'?geographyColor(p):legacyColor(id,p);
const riverPaths=(id:string)=>id==='elaris'?elaris.rivers.map(r=>r.points):legacyRivers(id);
const riverLevel=(id:string,z:number)=>id==='elaris'?elaris.level(z):legacyLevel(id,z);
const riverSurface=(id:string,x:number,z:number)=>id==='elaris'?elaris.level(z):legacySurface(id,x,z);
const lakes=(id:string)=>id==='elaris'?elaris.data.hydrology.lakes.map(l=>[l.x,l.z,l.rx,l.rz]):legacyLakes(id);
import type {ContinentId} from './world-data';

export type SceneOptions={continent:ContinentId;quality:'mobile'|'balanced'|'high';hour:number;weather:'clear'|'mist'|'rain';onReady:()=>void;onError:(message:string)=>void;onPosition:(p:{x:number;z:number;heading:number;biome:string;altitude:number;cameraAltitude:number;region:string;fps:number;triangles:number;drawCalls:number;frameMs:number;tiles:number;instances:number})=>void;onSpecimen:(id:string)=>void};
export type WorldScene={dispose:()=>void;travel:(x:number,z:number,close?:boolean)=>void;setHour:(hour:number)=>void;setWeather:(weather:'clear'|'mist'|'rain')=>void;setMode:(mode:'survey'|'ground'|'flight')=>void;setSpeed:(speed:number)=>void;setMotion:(x:number,y:number)=>void;setVertical:(v:number)=>void;setBoost:(v:boolean)=>void;resetInput:()=>void;setInputEnabled:(v:boolean)=>void;setPaused:(paused:boolean)=>void;setSpecimens:(show:boolean)=>void;exportHeightmap:()=>void};
const UP=new THREE.Vector3(0,1,0);
export function createWorldScene(host:HTMLElement,options:SceneOptions):WorldScene{
 const id=options.continent,EXTENT=extentFor(id),large=id==='elaris',high=options.quality==='high',mobile=options.quality==='mobile',preset=qualityPresets[options.quality],scene=new THREE.Scene();
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,preset.pixelRatio));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=high;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);
 renderer.domElement.setAttribute('aria-label','Interactive three-dimensional terrain of '+id);renderer.domElement.tabIndex=0;
 const camera=new THREE.PerspectiveCamera(53,host.clientWidth/host.clientHeight,.5,large?300000:12000);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=7;controls.maxDistance=3600;controls.maxPolarAngle=Math.PI*.485;controls.screenSpacePanning=false;controls.zoomToCursor=true;controls.target.set(80,60,120);camera.position.set(350,310,510);
 controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};
 const ambient=new THREE.HemisphereLight(0xc6e7ed,0x29362b,2);scene.add(ambient);
 const sun=new THREE.DirectionalLight(0xffe5bd,3.2);sun.position.set(-400,650,300);sun.castShadow=high;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-450;sun.shadow.camera.right=450;sun.shadow.camera.top=450;sun.shadow.camera.bottom=-450;sun.shadow.camera.far=2000;sun.shadow.normalBias=1.5;sun.shadow.bias=-.0004;scene.add(sun,sun.target);
 const sky=new Sky();sky.scale.setScalar(large?250000:9000);scene.add(sky);const skyUniforms=sky.material.uniforms;skyUniforms.turbidity.value=3;skyUniforms.rayleigh.value=1.5;skyUniforms.mieCoefficient.value=.004;skyUniforms.mieDirectionalG.value=.82;
 let hour=options.hour,weather=options.weather,mode:'survey'|'ground'|'flight'='survey',speed=1,paused=false,disposed=false,raf=0,elapsed=0;
 const fogColor=new THREE.Color(),sunPosition=new THREE.Vector3();
 function lighting(){const theta=(hour-6)/12*Math.PI,elevation=Math.sin(theta);sunPosition.set(Math.cos(theta),Math.max(-.2,elevation),-.35).normalize();skyUniforms.sunPosition.value.copy(sunPosition);sun.position.copy(sunPosition).multiplyScalar(900);const daylight=THREE.MathUtils.clamp(elevation*1.6,0,1);sun.intensity=(weather==='rain'?1.3:3.2)*daylight;sun.color.set(daylight<.45?0xffbb7c:0xffedce);ambient.intensity=.15+daylight*(weather==='rain'?1.1:1.2);ambient.color.set(daylight<.1?0x435d92:0xc6e1e9);fogColor.set(daylight<.1?0x111e32:weather==='rain'?0x637c86:id==='sahrel'?0xb0b3a5:0x98b9bd);scene.fog=new THREE.FogExp2(fogColor,(large?.018:1)*(weather==='mist'?.0015:weather==='rain'?.0009:id==='nythrune'?.0007:.00034));renderer.setClearColor(fogColor);renderer.toneMappingExposure=.65+daylight*.3;}
 lighting();
 const terrainGeometry=new THREE.PlaneGeometry(EXTENT*2.25,EXTENT*2.25,large?1:high?360:240,large?1:high?360:240);terrainGeometry.rotateX(-Math.PI/2);const pos=terrainGeometry.attributes.position,colors=new Float32Array(pos.count*3);
 for(let i=0;i<pos.count;i++){const p=sample(id,pos.getX(i),pos.getZ(i));pos.setY(i,p.height);colors.set(terrainColor(id,p),i*3);}terrainGeometry.setAttribute('color',new THREE.BufferAttribute(colors,3));terrainGeometry.computeVertexNormals();
 const terrainMaterial=createTerrainMaterial(large,options.quality);
 const terrain=new THREE.Mesh(terrainGeometry,terrainMaterial);terrain.receiveShadow=true;if(!large)scene.add(terrain);
 const geographicTerrain=large?createGeographicTerrain(scene,terrainMaterial,high):null;
 const ecology=large?createLocalEcology(scene,high,mobile?.5:1):null;
 const waterUniform={value:0};const waterMaterial=createWaterMaterial(waterUniform,'river',options.quality),oceanMaterial=createWaterMaterial(waterUniform,'ocean',options.quality),lakeMaterial=createWaterMaterial(waterUniform,'lake',options.quality);
 const oceanGeometry=new THREE.PlaneGeometry(large?500000:11000,large?500000:11000,high?180:80,high?180:80);oceanGeometry.rotateX(-Math.PI/2);const ocean=new THREE.Mesh(oceanGeometry,oceanMaterial);ocean.position.y=0;scene.add(ocean);
 for(const [pathIndex,path] of riverPaths(id).entries()){if(large){const stations=elaris.rivers[pathIndex].stations,vertices:number[]=[],indices:number[]=[],hydro:number[]=[];stations.forEach((p,i)=>{for(const cross of [-1,-.5,0,.5,1]){vertices.push((p.x-p.tz*p.width*cross)*EXTENT,p.level+.12,(p.z+p.tx*p.width*cross)*EXTENT);hydro.push(Math.max(.12,p.depth*(1-cross*cross)),p.tx,p.tz);}if(i)for(let k=0;k<4;k++){const a=(i-1)*5+k,b=i*5+k;indices.push(a,b,a+1,a+1,b,b+1)}});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('hydro',new THREE.Float32BufferAttribute(hydro,3));g.setIndex(indices);g.computeVertexNormals();scene.add(new THREE.Mesh(g,waterMaterial));continue;}const vertices:number[]=[],indices:number[]=[];let n=0;for(let s=1;s<path.length;s++){const [ax,az]=path[s-1],[bx,bz]=path[s],len=Math.hypot(bx-ax,bz-az),steps=Math.max(2,Math.ceil(len*(large?1000:180)));for(let j=0;j<=steps;j++){const t=j/steps,x=THREE.MathUtils.lerp(ax,bx,t),z=THREE.MathUtils.lerp(az,bz,t),w=(large?elaris.data.hydrology.rivers[pathIndex].width:id==='caelune'?.009:.011)*EXTENT;const dx=(bx-ax)/len,dz=(bz-az)/len,y=riverSurface(id,x,z)+.12;vertices.push(x*EXTENT-dz*w,y,z*EXTENT+dx*w,x*EXTENT+dz*w,y,z*EXTENT-dx*w);if(n>0)indices.push(n*2-2,n*2,n*2-1,n*2-1,n*2,n*2+1);n++;}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();scene.add(new THREE.Mesh(g,waterMaterial));}
 if(large)for(const lake of elaris.lakeShapes){const vertices:number[]=[lake.x*EXTENT,lake.level+.12,lake.z*EXTENT],hydro:number[]=[25,0,0],indices:number[]=[];for(const r of [.45,.8,1])for(const [x,z]of lake.points){vertices.push((lake.x+(x-lake.x)*r)*EXTENT,lake.level+.12,(lake.z+(z-lake.z)*r)*EXTENT);hydro.push(Math.max(.15,25*(1-r*r)),0,0);}const n=lake.points.length;for(let i=0;i<n;i++){const j=(i+1)%n;indices.push(0,1+j,1+i);for(let ring=0;ring<2;ring++){const a=1+ring*n+i,b=1+ring*n+j,c=a+n,d=b+n;indices.push(a,b,c,b,d,c);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('hydro',new THREE.Float32BufferAttribute(hydro,3));g.setIndex(indices);g.computeVertexNormals();scene.add(new THREE.Mesh(g,lakeMaterial));}
 for(const [x,z,sx,sz]of (large?[]:lakes(id))){const g=new THREE.CircleGeometry(1,64);g.rotateX(-Math.PI/2);const m=new THREE.Mesh(g,waterMaterial);m.scale.set(sx*EXTENT,1,sz*EXTENT);m.position.set(x*EXTENT,(large?elaris.level(elaris.data.hydrology.lakes.find(l=>l.x===x&&l.z===z)!.outletZ):riverLevel(id,z))+.2,z*EXTENT);scene.add(m);}
 // Supply physical depth / flow metadata to every water mesh, including legacy prototypes.
 scene.traverse(o=>{if(o instanceof THREE.Mesh&&[waterMaterial,oceanMaterial,lakeMaterial].includes(o.material as THREE.MeshStandardMaterial)&&!o.geometry.getAttribute('hydro')){const p=o.geometry.getAttribute('position'),h:number[]=[];for(let i=0;i<p.count;i++){const x=p.getX(i)*o.scale.x+o.position.x,z=p.getZ(i)*o.scale.z+o.position.z,y=p.getY(i)+o.position.y,ground=large?elaris.surface(x/EXTENT,z/EXTENT).height:sample(id,x,z).height;h.push(Math.max(.15,y-ground),.7,.3);}o.geometry.setAttribute('hydro',new THREE.Float32BufferAttribute(h,3));}});
 // Shared instanced geometry keeps the vegetation and geology render cost bounded.
 const dummy=new THREE.Object3D(),color=new THREE.Color();let seed=17;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
 const trunks:Array<{x:number;y:number;z:number;s:number;r:number}>=[],conifers:typeof trunks=[],broad:typeof trunks=[],rocks:typeof trunks=[],grass:typeof trunks=[];
 const attempts=large?0:Math.round(12500*preset.vegetation);
 for(let i=0;i<attempts;i++){const x=(random()*2-1)*EXTENT,z=(random()*2-1)*EXTENT,p=sample(id,x,z);if(p.coast<.028||p.height<3||p.water||p.river<.023)continue;
  const slope=Math.abs(sample(id,x+4,z).height-p.height)+Math.abs(sample(id,x,z+4).height-p.height);if(slope>12){if(random()<.13)rocks.push({x,y:p.height-1,z,s:2+random()*7,r:random()*6.28});continue;}
  const lush=['forest','jungle','tropical','highland'].includes(p.biome),arid=['desert','salt','dune','volcanic','ash','snow'].includes(p.biome);
  const grove=Math.hypot(x-270,z-180)<40;if(!grove&&lush&&random()<(id==='nythrune'?.72:.40)){
   const s=(id==='nythrune'?18:id==='thyrra'?12:8)+random()*(id==='nythrune'?24:18);const t={x,y:p.height,z,s,r:random()*6.28};trunks.push(t);if(id==='caelune'||p.biome==='highland'||(id==='elaris'&&z<100))conifers.push(t);else broad.push(t);
  }else if(!arid&&random()<.42)grass.push({x,y:p.height,z,s:1+random()*2,r:random()*6.28});
  if(random()<.045)rocks.push({x,y:p.height-.5,z,s:1+random()*5,r:random()*6.28});
 }
 const bark=new THREE.MeshStandardMaterial({color:0x514d3b,roughness:1}),foliage=new THREE.MeshStandardMaterial({color:0x507756,roughness:.85}),rockMat=new THREE.MeshStandardMaterial({color:id==='sahrel'?0x9c8064:0x666d63,roughness:.96});
 function instanced(g:THREE.BufferGeometry,m:THREE.Material,data:typeof trunks,kind:string){const inst=new THREE.InstancedMesh(g,m,data.length);for(let i=0;i<data.length;i++){const p=data[i];dummy.position.set(p.x,p.y,p.z);dummy.rotation.set(0,p.r,0);if(kind==='trunk'){dummy.position.y+=p.s*.4;dummy.scale.set(p.s*.035,p.s*.8,p.s*.035);}else if(kind==='conifer'){dummy.position.y+=p.s*.62;dummy.scale.set(p.s*.28,p.s*.88,p.s*.28);}else if(kind==='broad'){dummy.position.y+=p.s*.85;dummy.scale.set(p.s*.37,p.s*.32,p.s*.37);}else{dummy.scale.set(p.s,p.s*.65,p.s*.82);dummy.rotation.z=p.r*.2;}dummy.updateMatrix();inst.setMatrixAt(i,dummy.matrix);if(kind!=='trunk'){color.setHSL(kind==='rock'?.13:.27+random()*.06,kind==='rock'?.10:.19+random()*.22,kind==='rock'?.40:.23+random()*.12);inst.setColorAt(i,color);}}inst.castShadow=high&&kind!=='grass';inst.receiveShadow=true;scene.add(inst);return inst;}
 instanced(new THREE.CylinderGeometry(.7,1,1,6),bark,trunks,'trunk');
 const tiers:THREE.BufferGeometry[]=[];for(let i=0;i<5;i++){const cg=new THREE.ConeGeometry(1-i*.15,.50-i*.035,11,2);cg.translate(Math.sin(i*4)*.035,-.28+i*.17,Math.cos(i*4)*.035);const p=cg.attributes.position;for(let j=0;j<p.count;j++){const f=.88+noise(p.getX(j)*11+i,p.getZ(j)*11,9)*.24;p.setX(j,p.getX(j)*f);p.setZ(j,p.getZ(j)*f);}cg.computeVertexNormals();tiers.push(cg);}const coniferGeo=mergeGeometries(tiers);tiers.forEach(g=>g.dispose());instanced(coniferGeo,foliage,conifers,'conifer');
 const canopyGeo=new THREE.IcosahedronGeometry(1,mobile?0:1);const cp=canopyGeo.attributes.position;for(let i=0;i<cp.count;i++){const factor=.85+noise(cp.getX(i)*4,cp.getZ(i)*4,8)*.3;cp.setXYZ(i,cp.getX(i)*factor,cp.getY(i)*factor,cp.getZ(i)*factor);}canopyGeo.computeVertexNormals();instanced(canopyGeo,foliage,broad,'broad');
 instanced(new THREE.DodecahedronGeometry(1,1),rockMat,rocks,'rock');
 const grassGeo=new THREE.BufferGeometry();grassGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.35,0,0,0,1.4,.1,.2,0,0,0,0,-.3,.05,1.1,0,0,0,.3],3));grassGeo.computeVertexNormals();instanced(grassGeo,new THREE.MeshStandardMaterial({color:0x7c8653,side:THREE.DoubleSide,roughness:1}),grass,'grass');
 // Root buttresses convey Nythrune's layered ecology, without claiming a Firstroot location.
 if(id==='nythrune'&&!mobile){const roots=new THREE.Group();for(const t of trunks.filter((_,i)=>i%15===0).slice(0,70)){for(let a=0;a<3;a++){const angle=t.r+a*2.094;const end=new THREE.Vector3(t.x+Math.cos(angle)*t.s*.5,t.y+.5,t.z+Math.sin(angle)*t.s*.5);const start=new THREE.Vector3(t.x,t.y+t.s*.22,t.z);const delta=end.clone().sub(start);const m=new THREE.Mesh(new THREE.CylinderGeometry(.5,t.s*.065,delta.length(),5),bark);m.position.copy(start).add(end).multiplyScalar(.5);m.quaternion.setFromUnitVectors(UP,delta.normalize());roots.add(m);}}scene.add(roots);}
 if(id==='vulkara'){const lava=new THREE.MeshStandardMaterial({color:0xff6320,emissive:0xff3700,emissiveIntensity:2.2,roughness:.5});for(const [x,z,r]of[[-.12,-.40,.045],[.18,-.05,.036],[.30,.42,.029]]){const m=new THREE.Mesh(new THREE.CircleGeometry(r*EXTENT,48),lava);m.rotation.x=-Math.PI/2;m.position.set(x*EXTENT,sample(id,x*EXTENT,z*EXTENT).height+2,z*EXTENT);scene.add(m);}}
 const specimenGroup=new THREE.Group();scene.add(specimenGroup);const specimenMeshes:THREE.Object3D[]=[];
 const specimenObjects:Array<{group:THREE.Group;id:string;base:number}>=[];
 function makeSpecimen(speciesId:string,x:number,z:number,index:number){const root=new THREE.Group();root.userData.speciesId=speciesId;const base=sample(id,x,z).height;root.position.set(x,base,z);const scale=speciesId==='solavyr'?2.2:speciesId==='rosavyn'?1.35:1.6;root.scale.setScalar(scale);const green=new THREE.MeshStandardMaterial({color:speciesId==='rosavyn'?0x687346:0x55854b,roughness:.84}),dark=new THREE.MeshStandardMaterial({color:0x51472f,roughness:.9}),red=new THREE.MeshStandardMaterial({color:0x9b473b,roughness:.83});
  const tube=(points:THREE.Vector3[],radius:number,mat:THREE.Material)=>{const m=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),14,radius,5,false),mat);root.add(m);return m};
  for(let k=0;k<5;k++){const a=k/5*Math.PI*2; tube([new THREE.Vector3(Math.cos(a)*.38,1.15,Math.sin(a)*.28),new THREE.Vector3(Math.cos(a)*.31,2.7,Math.sin(a)*.3),new THREE.Vector3(Math.cos(a)*.53,4,Math.sin(a)*.36),new THREE.Vector3(Math.cos(a)*.20,4.8,Math.sin(a)*.2)],.14,k%3===0&&speciesId==='tomavyn'?red:green);}
  for(const s of [-1,1]){tube([new THREE.Vector3(s*.35,1.65,0),new THREE.Vector3(s*.5,.8,.1),new THREE.Vector3(s*.6,.14,.05)],.17,green);tube([new THREE.Vector3(s*.50,3.95,0),new THREE.Vector3(s*.93,3.10,0),new THREE.Vector3(s*1.10,2.2,.16)],.13,green);for(let k=0;k<3;k++)tube([new THREE.Vector3(s*.60,.22,.05),new THREE.Vector3(s*(.65+k*.14),.08,.15+k*.22)],.06,dark);}
  const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.43,1),green);head.scale.set(.8,1.15,.85);head.position.y=4.75;root.add(head);
  // Leaves are actual geometry; clustered leaflets preserve ancestry cues in the blockout.
  const leafGeo=new THREE.BufferGeometry();leafGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,-.28,.48,.05,0,1,.0,0,0,0,0,1,0,.28,.48,.05],3));leafGeo.computeVertexNormals();const leafMat=new THREE.MeshStandardMaterial({color:speciesId==='solavyr'?0x65814d:0x386643,side:THREE.DoubleSide,roughness:.85});
  for(let k=0;k<14;k++){const a=k*2.4;const m=new THREE.Mesh(leafGeo,leafMat);m.position.set(Math.cos(a)*.42,1.8+(k%5)*.46,Math.sin(a)*.35);m.rotation.set(.3, -a,Math.cos(a)*1.1);m.scale.setScalar(speciesId==='solavyr'?1.3:.70);root.add(m);}
  if(speciesId==='rosavyn'||speciesId==='solavyr'||speciesId==='lilavyn'||speciesId==='irivyn'||speciesId==='lilloryn'){const flower=new THREE.Group();flower.position.set(speciesId==='rosavyn'?.72:0,speciesId==='solavyr'?5.3:4.9,0);const petals=new THREE.MeshStandardMaterial({color:speciesId==='solavyr'?0xe9bc3f:speciesId==='lilavyn'||speciesId==='irivyn'?0xa793bc:speciesId==='lilloryn'?0xf0d6b6:0xd79797,side:THREE.DoubleSide,roughness:.75});const count=speciesId==='solavyr'?18:speciesId==='irivyn'||speciesId==='lilloryn'?6:12;for(let k=0;k<count;k++){const a=k/count*Math.PI*2,m=new THREE.Mesh(new THREE.SphereGeometry(1,7,5),petals);m.scale.set(.13,speciesId==='solavyr'?.43:.25,.09);m.position.set(Math.sin(a)*.43,Math.cos(a)*.43,.04);m.rotation.z=-a;flower.add(m);}const disk=new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,.13,18),new THREE.MeshStandardMaterial({color:speciesId==='solavyr'?0x56452d:0xbc7b86}));disk.rotation.x=Math.PI/2;flower.add(disk);root.add(flower);}
  const stand=new THREE.Mesh(new THREE.CylinderGeometry(2.2,2.4,.18,32),new THREE.MeshStandardMaterial({color:0x586c60,roughness:.85}));stand.position.y=.05;root.add(stand);root.traverse(o=>{o.userData.speciesId=speciesId;if(o instanceof THREE.Mesh){o.castShadow=high;specimenMeshes.push(o);}});specimenGroup.add(root);specimenObjects.push({group:root,id:speciesId,base:index});}
 if(id==='elaris')for(const [i,s]of ['rosavyn','solavyr','tomavyn','lilavyn','irivyn','lilloryn'].entries())makeSpecimen(s,large?3000+i*11:245+i*11,large?-8400:180,i);
 specimenGroup.visible=false;
 // Atmosphere: sparse moving cloud masses, rainfall and nighttime stars.
 const cloudData:typeof trunks=[];for(let i=0;i<24;i++)cloudData.push({x:(random()-.5)*(large?120000:3500),y:large?5000+random()*2000:460+random()*260,z:(random()-.5)*(large?120000:3500),s:(80+random()*140)*(large?12:1),r:random()*6});const clouds=instanced(new THREE.IcosahedronGeometry(1,2),new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.24,depthWrite:false,roughness:1}),cloudData,'rock');for(let i=0;i<cloudData.length;i++){const p=cloudData[i];dummy.position.set(p.x,p.y,p.z);dummy.scale.set(p.s*1.2,p.s*.46,p.s*.8);dummy.rotation.set(0,p.r,0);dummy.updateMatrix();clouds.setMatrixAt(i,dummy.matrix);clouds.setColorAt(i,new THREE.Color(0xffffff));}clouds.instanceMatrix.needsUpdate=true;clouds.castShadow=false;
 const particleCount=high?1800:850,rainPositions=new Float32Array(particleCount*3);for(let i=0;i<particleCount;i++){rainPositions[i*3]=(random()-.5)*700;rainPositions[i*3+1]=random()*450;rainPositions[i*3+2]=(random()-.5)*700;}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPositions,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xc5dce1,size:1.4,transparent:true,opacity:.5,depthWrite:false}));scene.add(rain);
 const starsPos=new Float32Array(900*3);for(let i=0;i<900;i++){const a=random()*Math.PI*2,b=random()*Math.PI*.48;starsPos[i*3]=Math.sin(b)*Math.cos(a)*5000;starsPos[i*3+1]=Math.cos(b)*5000;starsPos[i*3+2]=Math.sin(b)*Math.sin(a)*5000;}const starsGeo=new THREE.BufferGeometry();starsGeo.setAttribute('position',new THREE.BufferAttribute(starsPos,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xcad6ed,size:2.5,sizeAttenuation:false}));scene.add(stars);
 const targetMarker=new THREE.Mesh(new THREE.RingGeometry(2.2,2.6,40),new THREE.MeshBasicMaterial({color:0xc9e0b5,side:THREE.DoubleSide,transparent:true,opacity:.8}));targetMarker.rotation.x=-Math.PI/2;targetMarker.visible=false;scene.add(targetMarker);
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),keys=new Set<string>();let frames=0,frameTime=0,measuredFps=0;let inputEnabled=true,vertical=0,boost=false;const activePointers=new Set<number>();let gestureMoved=false;let down={x:0,y:0},motion={x:0,y:0},destination:THREE.Vector3|null=null,lastTick=0;const clock=new THREE.Clock();
 function travel(x:number,z:number,close=false){let wx=x*EXTENT,wz=z*EXTENT,p=sample(id,wx,wz);if(mode==='ground'&&(p.water||p.height<0)){for(let r=10;r<(large?4000:150);r*=1.6){let found=false;for(let a=0;a<16;a++){const tx=wx+Math.cos(a*Math.PI/8)*r,tz=wz+Math.sin(a*Math.PI/8)*r,t=sample(id,tx,tz);if(t.height>0&&!t.water){wx=tx;wz=tz;p=t;found=true;break;}}if(found)break;}}const y=Math.max(p.height,p.water,0);destination=null;targetMarker.visible=false;controls.target.set(wx,y+3,wz);if(mode==='ground'){camera.position.set(wx,y+3,wz+6);}else camera.position.set(wx+(close?16:large?800:210),y+(close?10:large?700:180),wz+(close?24:large?1100:260));controls.update();}

 function pick(e:PointerEvent){activePointers.delete(e.pointerId);if(!inputEnabled||gestureMoved||e.button!==0||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);if(specimenGroup.visible){const hit=raycaster.intersectObjects(specimenMeshes,false)[0];if(hit){options.onSpecimen(hit.object.userData.speciesId);return;}}
  const hit=raycaster.intersectObjects(geographicTerrain?.meshes||[terrain],false)[0];if(hit){const p=sample(id,hit.point.x,hit.point.z);if(p.height<0||p.water>p.height)return;destination=hit.point.clone();targetMarker.position.copy(hit.point);targetMarker.position.y+=.5;targetMarker.visible=true;}}
 const pointerDown=(e:PointerEvent)=>{if(!inputEnabled)return;activePointers.add(e.pointerId);if(activePointers.size===1){down={x:e.clientX,y:e.clientY};gestureMoved=false}else gestureMoved=true;renderer.domElement.focus({preventScroll:true})};
 const pointerMove=(e:PointerEvent)=>{if(activePointers.has(e.pointerId)&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)gestureMoved=true};const pointerCancel=(e:PointerEvent)=>{activePointers.delete(e.pointerId);gestureMoved=true;destination=null};
 const keyDown=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','PageUp','PageDown','Shift'].includes(e.key)){e.preventDefault();keys.add(e.key)}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key);const blur=()=>{keys.clear();motion={x:0,y:0};vertical=0;boost=false;destination=null;activePointers.clear();gestureMoved=true};
 renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointercancel',pointerCancel);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pick);renderer.domElement.addEventListener('keydown',keyDown);renderer.domElement.addEventListener('keyup',keyUp);renderer.domElement.addEventListener('blur',blur);
 const lost=(e:Event)=>{e.preventDefault();options.onError('The 3D graphics context was interrupted. Reload the scene or switch to Balanced detail.');};renderer.domElement.addEventListener('webglcontextlost',lost);
 const resize=new ResizeObserver(()=>{if(disposed)return;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(host);
 function tick(){if(disposed)return;raf=requestAnimationFrame(tick);const rawDt=clock.getDelta(),dt=Math.min(rawDt,.05);if(paused||document.hidden)return;elapsed+=dt;frames++;frameTime+=rawDt;if(frameTime>1){measuredFps=frames/frameTime;frames=0;frameTime=0;}waterUniform.value=elapsed;controls.update();
  const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,UP).normalize();const mx=motion.x+(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),my=-motion.y+(keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0);const move=forward.multiplyScalar(my).add(right.multiplyScalar(mx));
  if(move.lengthSq()>0){destination=null;move.normalize().multiplyScalar(dt*speed*(keys.has('Shift')||boost?4:1)*(mode==='ground'?6:large?900:100));}else if(destination){move.copy(destination).sub(controls.target);move.y=0;const distance=move.length();if(distance<3){destination=null;targetMarker.visible=false;move.set(0,0,0);}else move.normalize().multiplyScalar(Math.min(distance,dt*speed*(keys.has('Shift')||boost?4:1)*(mode==='ground'?6:large?900:130)));}
  if(move.lengthSq()>0){const candidate=controls.target.clone().add(move);candidate.x=THREE.MathUtils.clamp(candidate.x,-EXTENT,EXTENT);candidate.z=THREE.MathUtils.clamp(candidate.z,-EXTENT,EXTENT);const p=sample(id,candidate.x,candidate.z);if(mode!=='ground'||(p.height>0&&!p.water)){const prevY=controls.target.y;controls.target.x=candidate.x;controls.target.z=candidate.z;if(mode!=='flight')controls.target.y=THREE.MathUtils.lerp(prevY,Math.max(0,p.height,p.water)+3,Math.min(1,dt*8));camera.position.add(move);camera.position.y+=controls.target.y-prevY;}else destination=null;}
  if(mode==='flight'){const dy=(vertical+(keys.has('PageUp')?1:0)-(keys.has('PageDown')?1:0))*dt*speed*(large?700:80);camera.position.y+=dy;controls.target.y+=dy;}
  const camGround=sample(id,camera.position.x,camera.position.z);camera.position.y=mode==='ground'?Math.max(camGround.height,camGround.water,0)+3:Math.max(camera.position.y,camGround.height+3,camGround.water+3,3);const targetGround=sample(id,controls.target.x,controls.target.z);controls.target.y=Math.max(controls.target.y,targetGround.height+1);sun.target.position.copy(controls.target);sun.position.copy(controls.target).addScaledVector(sunPosition,900);rain.visible=weather==='rain';rain.position.set(camera.position.x,camera.position.y-200,camera.position.z);if(rain.visible){const attr=rainGeo.attributes.position;for(let i=0;i<particleCount;i++){let y=attr.getY(i)-dt*130;if(y<0)y=450;attr.setY(i,y);}attr.needsUpdate=true;}stars.visible=hour<6||hour>19;clouds.rotation.y=elapsed*.0008;for(const s of specimenObjects)s.group.rotation.z=Math.sin(elapsed*.55+s.base)*.009;
  if(elapsed-lastTick>.25){lastTick=elapsed;const p=sample(id,controls.target.x,controls.target.z),direction=new THREE.Vector3();camera.getWorldDirection(direction);let instances=0;scene.traverse(o=>{if(o instanceof THREE.InstancedMesh&&o.visible)instances+=o.count});options.onPosition({frameMs:measuredFps?1000/measuredFps:0,tiles:geographicTerrain?.stats().tiles||1,instances,x:controls.target.x/EXTENT,z:controls.target.z/EXTENT,heading:(Math.atan2(direction.x,-direction.z)*180/Math.PI+360)%360,biome:p.biome,altitude:p.height,cameraAltitude:camera.position.y,region:large?elaris.sample(controls.target.x,controls.target.z).region:'Prototype region',fps:measuredFps,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls});}geographicTerrain?.update(camera.position.x,camera.position.z,camera.position.y-camGround.height);ecology?.update(camera.position.x,camera.position.z,camera.position.y-camGround.height);renderer.render(scene,camera);
 }
 controls.maxDistance=large?180000:3600;travel(large?.055:.1,large?-.14:.1);tick();options.onReady();
 return {travel,resetInput:blur,setInputEnabled(v){inputEnabled=v;controls.enabled=v;if(!v)blur()},setVertical(v){vertical=v},setBoost(v){boost=v},setSpeed(v){speed=THREE.MathUtils.clamp(v,.25,32)},setHour(h){hour=h;lighting()},setWeather(w){weather=w;lighting()},setMode(m){blur();mode=m;destination=null;const offset=camera.position.clone().sub(controls.target).normalize();camera.position.copy(controls.target).addScaledVector(offset,m==='ground'?6:large?1200:330);controls.minDistance=m==='ground'?3:12;controls.maxDistance=m==='ground'?12:large?180000:3600;controls.enablePan=m!=='ground';controls.maxPolarAngle=m==='flight'?Math.PI*.98:Math.PI*.485;controls.update();},setMotion(x,y){motion={x,y}},setPaused(v){paused=v;if(v)blur()},setSpecimens(show){specimenGroup.visible=show;if(show&&id==='elaris')travel((large?3033:273)/EXTENT,(large?-8400:180)/EXTENT,true)},exportHeightmap(){const size=257,values=[];for(let z=0;z<size;z++)for(let x=0;x<size;x++)values.push(Math.round(sample(id,(x/(size-1)*2-1)*EXTENT,(z/(size-1)*2-1)*EXTENT).height*100)/100);const blob=new Blob([JSON.stringify({continent:id,status:'EXPERIMENTAL_INTERPRETATION',source:'Seedwoken Codex v1.6',size,extent:EXTENT*2,units:large?'experimental model metres, not canonical dimensions':'prototype units, not canonical metres',geography:large?elaris.data:undefined,heights:values})],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`vaelora-${id}-heightmap.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},dispose(){disposed=true;cancelAnimationFrame(raf);resize.disconnect();controls.dispose();ecology?.dispose();if(large)terrainGeometry.dispose();renderer.domElement.removeEventListener('pointermove',pointerMove);renderer.domElement.removeEventListener('pointercancel',pointerCancel);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pick);renderer.domElement.removeEventListener('keydown',keyDown);renderer.domElement.removeEventListener('keyup',keyUp);renderer.domElement.removeEventListener('blur',blur);renderer.domElement.removeEventListener('webglcontextlost',lost);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.InstancedMesh)o.dispose();if(o instanceof THREE.Mesh||o instanceof THREE.Points){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();}};
}
