export type ContinentId = 'elaris'|'sahrel'|'caelune'|'vulkara'|'thyrra'|'nythrune';
export const continents = [
 {id:'elaris',name:'Elaris',title:'The Mainland',color:'#87b584',reference:'/world/references/elaris.webp',status:'Reference-grounded',description:'Follow the Vaelorin from northern lake country through temperate forests to the southern wetland delta.',biomes:['Northern highlands','Temperate forest','River meadows','Southern wetlands'],canon:'The Vaelorin is the greatest known river of Vaelora. Silren, Mossrun, Avenwater, Briarwash and Orin’s Fork are tributaries or regional rivers. The accepted map anchors the coast, western islands, southwestern bay, highlands and southern archipelagos.',places:[{name:'Vaelorin river country',x:.10,z:.10},{name:'Northern lake country',x:.09,z:-.56},{name:'Southern delta',x:.15,z:.65},{name:'Western island coast',x:-.57,z:.20}],open:'Local river bends, tributary locations, vegetation density, travel distances and specimen placement are interpretations.'},
 {id:'sahrel',name:'Sahrel',title:'The Sunscar',color:'#d7ac70',reference:'/world/references/sahrel.webp',status:'Reference-grounded',description:'Cross an immense arid basin, fossil drainage networks, salt flats and plateau country that remembers a wetter age.',biomes:['Desert plateau','Salt basin','Dune country','Water corridor'],canon:'The Sunscar basin is enclosed by high plateaus. A northern remnant lake, ancient drainage, canyon country, southern dunes and a surviving southern water corridor anchor the accepted reference. Rare rains awaken dormant seed banks.',places:[{name:'Sunscar basin',x:.08,z:-.03},{name:'Northern remnant lake',x:.12,z:-.62},{name:'Southern water corridor',x:.08,z:.65},{name:'Western plateau',x:-.48,z:.05}],open:'Canyon detail, aquifer extent, dune shapes and oasis placement remain interpreted. This trial does not establish a rainfall calendar.'},
 {id:'caelune',name:'Caelune',title:'The Crown',color:'#b7d7df',reference:'/world/references/caelune.webp',status:'Reference-grounded',description:'Rise through the Crownspine, where glacial basins feed western fjords, high lakes and a south-flowing watershed.',biomes:['Western mountain forest','Crownspine','Glacial highlands','Eastern cold steppe'],canon:'Mount Aevor is the highest known mountain: split summit horns around an ancient glacial basin. Its approximate upper-central position is established; the continental plate does not finalize local summit morphology.',places:[{name:'Mount Aevor',x:.02,z:-.46},{name:'Western forest and fjords',x:-.48,z:.04},{name:'Eastern rain shadow',x:.43,z:.18},{name:'Southern meltwater corridor',x:.10,z:.61}],open:'The split-crown model is provisional. Actual elevation, scale, valley names and mountain microstructure are unresolved.'},
 {id:'vulkara',name:'Vulkara',title:'The Broken Furnace',color:'#ee9b70',reference:'/world/references/vaelora.webp',status:'Provisional geography',description:'Explore a restless volcanic province of ash, basalt, geothermal water and young island arcs.',biomes:['Cinderwake','Ash slopes','Recolonizing lowlands','Volcanic coast'],canon:'The Cinderwake crosses an active tectonic province and continues offshore through island arcs. Earthquakes, ashfall, fumaroles, acidic soils and unstable ground shape repeated destruction and recolonization.',places:[{name:'Cinderwake volcanic belt',x:.00,z:-.26},{name:'Recolonizing lowlands',x:-.40,z:.40},{name:'Offshore island arc',x:.52,z:.60}],open:'No dedicated accepted continental map was recovered. Coastline, volcano locations and lava paths in this scene are proposed visual interpretations.'},
 {id:'thyrra',name:'Thyrra',title:'The Thousand Shores',color:'#69d8c8',reference:'/world/references/vaelora.webp',status:'Provisional geography',description:'Travel between drowned valleys, forested islands, tidal wetlands and turquoise shallows.',biomes:['Inland highlands','Tropical forest','Tidal wetlands','Reef shallows'],canon:'An ancient continental mass fragmented by rifting and rising seas. The Thousand Shores is a poetic name, not a surveyed island count. Aquatic and amphibious Phyvera are future study directions.',places:[{name:'The Thousand Shores',x:-.17,z:.06},{name:'Northern highland island',x:.06,z:-.53},{name:'Southern shallows',x:.12,z:.51}],open:'Island shapes, reef placement, tides and local species distributions are provisional; the globe does not define canonical planetary coordinates.'},
 {id:'nythrune',name:'Nythrune',title:'The Veiled Wilds',color:'#83ad9a',reference:'/world/references/vaelora.webp',status:'Provisional geography',description:'Enter a layered forest and wetland realm where immense roots and competition shape the landscape.',biomes:['Upper canopy','The Veil','Root wetlands','Ancient uplands'],canon:'Ancient stable terrain supports multilayer forests, parasitic plants, fungal networks and defensive vegetation. The Firstroot remains unresolved: organism, geological structure, unusual Vael site or myth.',places:[{name:'The Veil',x:.08,z:.00},{name:'Root wetlands',x:.20,z:.48},{name:'Ancient uplands',x:-.32,z:-.42}],open:'No Firstroot object or location is asserted. Coastline, forest structure and local terrain here are experimental.'}
] as const;
export const species = [
 {id:'rosavyn',number:'001',name:'Rosavyn',ancestry:'Rosa spp.',status:'Established',image:'/world/references/rosavyn-adult.webp',description:'A mobile rose: intertwined living canes, compound serrated leaves, curved retractable prickles and rootlike feet. Female dominant bloom at the crown; male bloom at shoulder or upper back.',biology:'Briarhold extends and interlocks existing young canes at a cost in water and carbohydrates. Veyra affects tissue pigmentation; flower color is inherited separately.',unknown:'Exact maturation age and male/female reproductive roles are unresolved.'},
 {id:'solavyr',number:'002',name:'Solavyr',ancestry:'Helianthus spp.',status:'Established',image:'/world/references/solavyr-male.webp',description:'Reinforced herbaceous stalks, coarse trichomes and large sunflower leaves. Male capitulum faces forward. Female capitulum faces backward on a separate reinforced upper-back peduncle.',biology:'Sunbrace redistributes fibrous tension, spreads root-feet and lowers the center of gravity. Overuse strains tissues and vascular structures. Young individuals show stronger heliotropism.',unknown:'Geographic range and most lifecycle visuals remain open. “Helivyn” in an exploratory atlas is not the accepted name.'},
 {id:'tomavyn',number:'003',name:'Tomavyn',ancestry:'Solanum lycopersicum',status:'Active development',image:'/world/references/tomavyn.webp',description:'Living herbaceous green tissue with integrated red carotenoid-rich storage corridors, fine glandular trichomes and true tomato leaves.',biology:'The adult male direction has broader shoulders, a wider torso and greater green dominance. Red anatomy must not resemble attached tomatoes, paint or exposed muscle.',unknown:'Lifecycle, reproduction, geographic range and detailed ecology are not finalized.'},
 {id:'lilavyn',number:'004',name:'Lilavyn',ancestry:'Syringa vulgaris',status:'Locked concept',image:'/world/references/lilavyn.webp',description:'A lilac-derived concept grounded in opposite simple leaves, terminal flower panicles, fragrant tubular flowers and multiple woody stems.',biology:'Fragrance signaling, pollinator relationships, seasonal flowering and vegetative recovery are concept directions, not finalized mechanisms.',unknown:'Anatomy, sex differences, defenses, lifecycle, Veyra and geographic placement remain provisional. The poster’s “Species 002” label is superseded.'},
 {id:'irivyn',number:'005',name:'Irivyn',ancestry:'Iris spp. — ancestral clade open',status:'Locked concept',image:'/world/references/irivyn.webp',description:'Herbaceous perennial anatomy, sword-shaped foliage, three outer floral falls and three inner standards. The precise storage-organ and habitat lineage remains open.',biology:'Rhizome or bulb reserves support seasonal renewal. Regeneration is gradual and depends on healthy storage tissue, foliage, water and nutrients.',unknown:'Region, Veyra, lifecycle and abilities remain provisional. Bioluminescence and supernatural water sensing on the poster are not canon.'},
 {id:'lilloryn',number:'006',name:'Lilloryn',ancestry:'Lilium spp. — true lilies',status:'Locked concept',image:'/world/references/lilloryn.webp',description:'Upright herbaceous growth, underground bulb reserves, parallel-veined leaves and flowers with six tepals and six stamens surrounding a central style and ovary.',biology:'Bulb reserves support seasonal dormancy and regrowth. Basal-plate damage and persistent waterlogging are serious threats. True-lily ancestry does not make this species aquatic.',unknown:'Replaces rejected Nymphara and Mycelith concepts. Poster healing, water-filtration, rapid regeneration, Veyra and habitat claims remain unapproved.'}
] as const;
export const sexDifferences:Record<string,{status:string;description:string}>={
 rosavyn:{status:'Established bloom placement · reproductive roles open',description:'Females carry the dominant bloom at the crown; males at the shoulder or upper back. Rosa flowers are usually bisexual. Separate Phyveran sexes are a post-Kindling specialization, with precise pollen/ovule roles still unresolved.'},
 solavyr:{status:'Established architecture · proposed mechanism',description:'Male capitula face forward. Female capitula face backward on a separate upper-back peduncle that supports increasing seed mass. A pollen-biased male and seed-biased female investment system is proposed; it is not ordinary sunflower sex biology.'},
 tomavyn:{status:'Established visual traits · proposed reproductive specialization',description:'Broader male shoulders and greater green dominance are secondary traits. Proposed male floral clusters emphasize pollen; female clusters emphasize stigma, ovary and seed-bearing structures. Earth tomato flowers normally contain both reproductive functions.'},
 lilavyn:{status:'Proposed biological direction',description:'Proposed males emphasize pollen-biased panicles and lighter reproductive loading; females emphasize ovule/fruit-biased panicles, capsules and seed maturation. Fragrance matters in both sexes. This is a derived specialization, not the ordinary lilac condition.'},
 irivyn:{status:'Proposed biological direction',description:'Proposed males emphasize anthers, pollen and floral display; females emphasize stigmatic tissue, ovaries, capsules and seed provisioning. Flower orientation, organ proportions, storage and seasonal condition may distinguish sex more reliably than overall body shape.'},
 lilloryn:{status:'Proposed biological direction',description:'Proposed males emphasize elongated stamens, anthers, pollen and display; females emphasize stigma/style/ovary, three-part capsules, seed provisioning and bulb reserves. Individuals may be difficult to sex outside flowering season. Both retain true-lily anatomy.'}
};
export const lifecycle=['Seed','Seedling','Kindling','Seedform','Infant','Mid Stage','Adult'];
