/* eslint-disable @typescript-eslint/no-explicit-any */
import { z } from "zod";
export const intelligenceRequest=z.object({action:z.enum(["explain","analyze","plausibility","canon","conflict","compare","ancestry","adaptation","development","dimorphism","propose","prompt"]),profile:z.enum(["quick","biology","conflict","visual","deep"]).default("biology"),speciesId:z.string().max(80),stage:z.string().max(80).optional(),sex:z.string().max(80).optional(),veyra:z.string().max(80).optional(),system:z.string().max(120).optional(),selectedRecordIds:z.array(z.number().int()).max(30).default([]),selectedVisualIds:z.array(z.number().int()).max(12).default([]),question:z.string().trim().max(2000).default("")});
const stringArray=z.array(z.string());
export const intelligenceResult=z.object({summary:z.string(),plainLanguageExplanation:z.string(),technicalExplanation:z.string(),evidence:stringArray,canonSupport:stringArray,realBiologySupport:stringArray,inferences:stringArray,proposals:stringArray,conflicts:stringArray,unknowns:stringArray,affectedSystems:stringArray,suggestedChanges:stringArray,sourceReferences:stringArray});
export type IntelligenceContext={species:Record<string,unknown>|null;biology:Record<string,unknown>[];knowledge:Record<string,unknown>[];visuals:Record<string,unknown>[];canon:Record<string,unknown>[];focus:Record<string,string>;question:string}; export type IntelligenceResult=z.infer<typeof intelligenceResult>;
const rank=(r:Record<string,unknown>,i:z.infer<typeof intelligenceRequest>)=>Number(r.speciesId===i.speciesId)*20+Number(i.stage&&r.stage===i.stage)*9+Number(i.sex&&r.sex===i.sex)*7+Number(i.veyra&&r.veyraName===i.veyra)*7+Number(i.system&&(r.section===i.system||r.entityType===i.system))*6;
export function buildContext(input:z.infer<typeof intelligenceRequest>,data:{species:Record<string,unknown>[];biology:Record<string,unknown>[];knowledge:Record<string,unknown>[];visuals:Record<string,unknown>[];canon:Record<string,unknown>[]}):IntelligenceContext{const selected=(ids:number[],r:Record<string,unknown>)=>!ids.length||ids.includes(Number(r.id));const relevant=(rows:Record<string,unknown>[],max:number)=>rows.filter(r=>(r.speciesId===input.speciesId||r.speciesId==null)&&r.supersededBy==null).sort((a,b)=>rank(b,input)-rank(a,input)).slice(0,max);return {species:data.species.find(r=>r.id===input.speciesId)||null,biology:relevant(data.biology.filter(r=>selected(input.selectedRecordIds,r)),24),knowledge:relevant(data.knowledge.filter(r=>selected(input.selectedRecordIds,r)),30),visuals:relevant(data.visuals.filter(r=>selected(input.selectedVisualIds,r)),12),canon:relevant(data.canon,20),focus:Object.fromEntries(Object.entries({stage:input.stage||"",sex:input.sex||"",veyra:input.veyra||"",system:input.system||""}).filter(([,v])=>v)),question:input.question};}
export interface IntelligenceProvider{run(action:string,context:IntelligenceContext,profile:string):Promise<{data:IntelligenceResult;model:string;requestId?:string;usage?:unknown}>}
const keys=["summary","plainLanguageExplanation","technicalExplanation"],arrays=["evidence","canonSupport","realBiologySupport","inferences","proposals","conflicts","unknowns","affectedSystems","suggestedChanges","sourceReferences"];
const schema={type:"object",additionalProperties:false,required:[...keys,...arrays],properties:Object.fromEntries([...keys.map(k=>[k,{type:"string"}]),...arrays.map(k=>[k,{type:"array",items:{type:"string"}}])])};
const SYSTEM="You are PHYVERA's biological analysis provider. Use only supplied context. Never invent Seedwoken canon. Separate canon, real-biology support, inference, proposal, conflict, and unknown. Newer text never overrides canon. Proposed changes require human approval. Be concise and biologically rigorous.";
export class OpenAIProvider implements IntelligenceProvider{constructor(private key:string,private models:Record<string,string>){}async run(action:string,context:IntelligenceContext,profile:string){const model=this.models[profile]||this.models.biology;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${this.key}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:profile==="quick"?"low":profile==="deep"?"high":"medium"},input:[{role:"system",content:SYSTEM},{role:"user",content:JSON.stringify({action,context})}],text:{format:{type:"json_schema",name:"phyvera_analysis",strict:true,schema}}})});const raw=await response.json() as any;if(!response.ok)throw new Error(raw?.error?.message||`OpenAI ${response.status}`);const value=raw.output_text||raw.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==="output_text")?.text;if(!value)throw new Error("Provider returned no structured output");return {data:intelligenceResult.parse(JSON.parse(value)),model,requestId:raw.id,usage:raw.usage};}}
export function getIntelligenceProvider(config:{key?:string;models:Record<string,string>}):IntelligenceProvider|null{return config.key?new OpenAIProvider(config.key,config.models):null}
